In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
data_filename = "OnlineNewsPopularity.csv"

df = pd.read_csv(data_filename)
df.head()

,url,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.0,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.0,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.0,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.0,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505

In [3]:
df = df.drop(columns=["url", " timedelta"])

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39644 entries, 0 to 39643
Data columns (total 59 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0    n_tokens_title                 39644 non-null  float64
 1    n_tokens_content               39644 non-null  float64
 2    n_unique_tokens                39644 non-null  float64
 3    n_non_stop_words               39644 non-null  float64
 4    n_non_stop_unique_tokens       39644 non-null  float64
 5    num_hrefs                      39644 non-null  float64
 6    num_self_hrefs                 39644 non-null  float64
 7    num_imgs                       39644 non-null  float64
 8    num_videos                     39644 non-null  float64
 9    average_token_length           39644 non-null  float64
 10   num_keywords                   39644 non-null  float64
 11   data_channel_is_lifestyle      39644 non-null  float64
 12   data_channel_is_entertainment  39644 non-null  float64
 13   data_channel_is_bus            39644 non-null  float64
 14   data_channel_is_socmed         39644 non-null  float64
 15   data_channel_is_tech           39644 non-null  float64
 16   data_channel_is_world          39644 non-null  float64
 17   kw_min_min                     39644 non-null  float64
 18   kw_max_min                     39644 non-null  float64
 19   kw_avg_min                     39644 non-null  float64
 20   kw_min_max                     39644 non-null  float64
 21   kw_max_max                     39644 non-null  float64
 22   kw_avg_max                     39644 non-null  float64
 23   kw_min_avg                     39644 non-null  float64
 24   kw_max_avg                     39644 non-null  float64
 25   kw_avg_avg                     39644 non-null  float64
 26   self_reference_min_shares      39644 non-null  float64
 27   self_reference_max_shares      39644 non-null  float64
 28   self_reference_avg_sharess     39644 non-null  float64
 29   weekday_is_monday              39644 non-null  float64
 30   weekday_is_tuesday             39644 non-null  float64
 31   weekday_is_wednesday           39644 non-null  float64
 32   weekday_is_thursday            39644 non-null  float64
 33   weekday_is_friday              39644 non-null  float64
 34   weekday_is_saturday            39644 non-null  float64
 35   weekday_is_sunday              39644 non-null  float64
 36   is_weekend                     39644 non-null  float64
 37   LDA_00                         39644 non-null  float64
 38   LDA_01                         39644 non-null  float64
 39   LDA_02                         39644 non-null  float64
 40   LDA_03                         39644 non-null  float64
 41   LDA_04                         39644 non-null  float64
 42   global_subjectivity            39644 non-null  float64
 43   global_sentiment_polarity      39644 non-null  float64
 44   global_rate_positive_words     39644 non-null  float64
 45   global_rate_negative_words     39644 non-null  float64
 46   rate_positive_words            39644 non-null  float64
 47   rate_negative_words            39644 non-null  float64
 48   avg_positive_polarity          39644 non-null  float64
 49   min_positive_polarity          39644 non-null  float64
 50   max_positive_polarity          39644 non-null  float64
 51   avg_negative_polarity          39644 non-null  float64
 52   min_negative_polarity          39644 non-null  float64
 53   max_negative_polarity          39644 non-null  float64
 54   title_subjectivity             39644 non-null  float64
 55   title_sentiment_polarity       39644 non-null  float64
 56   abs_title_subjectivity         39644 non-null  float64
 57   abs_title_sentiment_polarity   39644 non-null  float64
 58   shares                         39644 non-null  int64
dtypes: float64(58), int64(1)
memory usage: 17.8 MB

In [5]:
df.describe()

,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,num_videos,average_token_length,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
count,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,...,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000,39644.000000
mean,10.398749,546.514731,0.548216,0.996469,0.689175,10.883690,3.293638,4.544143,1.249874,4.548239,...,0.095446,0.756728,-0.259524,-0.521944,-0.107500,0.282353,0.071425,0.341843,0.156064,3395.380184
std,2.114037,471.107508,3.520708,5.231231,3.264816,11.332017,3.855141,8.309434,4.107855,0.844406,...,0.071315,0.247786,0.127726,0.290290,0.095373,0.324247,0.265450,0.188791,0.226294,11626.950749
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,-1.000000,-1.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,1.000000
25%,9.000000,246.000000,0.470870,1.000000,0.625739,4.000000,1.000000,1.000000,0.000000,4.478404,...,0.050000,0.600000,-0.328383,-0.700000,-0.125000,0.000000,0.000000,0.166667,0.000000,946.000000
50%,10.000000,409.000000,0.539226,1.000000,0.690476,8.000000,3.000000,1.000000,0.000000,4.664082,...,0.100000,0.800000,-0.253333,-0.500000,-0.100000,0.150000,0.000000,0.500000,0.000000,1400.000000
75%,12.000000,716.000000,0.608696,1.000000,0.754630,14.000000,4.000000,4.000000,1.000000,4.854839,...,0.100000,1.000000,-0.186905,-0.300000,-0.050000,0.500000,0.150000,0.500000,0.250000,2800.000000
max,23.000000,8474.000000,701.000000,1042.000000,650.000000,304.000000,116.000000,128.000000,91.000000,8.041534,...,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.500000,1.000000,843300.000000

In [6]:
df[" data_channel_is_lifestyle"].value_counts()

 data_channel_is_lifestyle
0.0    37545
1.0     2099
Name: count, dtype: int64

In [7]:
df[" data_channel_is_bus"].value_counts()

 data_channel_is_bus
0.0    33386
1.0     6258
Name: count, dtype: int64

In [8]:
df[" data_channel_is_socmed"].value_counts()

 data_channel_is_socmed
0.0    37321
1.0     2323
Name: count, dtype: int64

In [9]:
df[" data_channel_is_tech"].value_counts()

 data_channel_is_tech
0.0    32298
1.0     7346
Name: count, dtype: int64

In [10]:
df[" data_channel_is_world"].value_counts()

 data_channel_is_world
0.0    31217
1.0     8427
Name: count, dtype: int64

In [11]:
df[" data_channel_is_entertainment"].value_counts()

 data_channel_is_entertainment
0.0    32587
1.0     7057
Name: count, dtype: int64

In [12]:
n_target = 50
n_source = 100

# target is data_channel_is_entertainment

In [13]:
def get_target_data(df, n_target):
    target_df = df[df[" data_channel_is_entertainment"] == 1]
    target_df = target_df.sample(n=n_target)

    X = target_df.drop(columns=[" shares"])
    y = target_df[" shares"]

    X_scaler = StandardScaler()
    y_scaler = StandardScaler()

    X_scaled = X_scaler.fit_transform(X)
    y_scaled = y_scaler.fit_transform(y.values.reshape(-1, 1)).ravel()

    target_data = {
        "X": X_scaled,
        "y": y_scaled
        # "y": y.to_numpy()
        # "y": y.to_numpy() - y.mean()  
    }
    return target_data

In [14]:
def get_source_data(df, n_source):
    columns = [" data_channel_is_lifestyle", " data_channel_is_bus", " data_channel_is_socmed", " data_channel_is_tech", " data_channel_is_world"]

    source_data = []
    for c in columns:
        source_df = df[df[c] == 1]
        source_df = source_df.sample(n=n_source)
        X = source_df.drop(columns=[" shares"])
        y= source_df[" shares"]

        X_scaler = StandardScaler()
        y_scaler = StandardScaler()

        X_scaled = X_scaler.fit_transform(X)
        y_scaled = y_scaler.fit_transform(y.values.reshape(-1, 1)).ravel()

        source_data.append({
            "X": X_scaled,
            # "y": y.to_numpy() - y.mean() 
            "y": y_scaled
            # "y": y.to_numpy()
        })

    return source_data

In [15]:
def estimate_Sigma(X, y, n):
    from sklearn.linear_model import LassoCV

    clf = LassoCV(cv=10, fit_intercept=False).fit(X, y)

    beta_hat = clf.coef_
    p_lambda = beta_hat[beta_hat != 0].shape[0]
    res = y - X @ beta_hat

    if p_lambda >= n:
        raise ValueError("p_lambda must be less than n to estimate Sigma.")

    sigma_squared = (1 / (n - p_lambda)) * np.sum(res ** 2)

    Sigma = sigma_squared * np.eye(n_target)
    return Sigma

In [16]:
beta_index_dict = {}

In [19]:
cd ./..

d:\Data Science Project\cort-si\Selective_Inference_For_CoRT

In [22]:
import CoRT_builder
from sklearn.linear_model import Lasso, LassoCV

import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)

p = df.shape[1] - 1
K = 5
T = 5
CONST_C = 0.15
iteration = 1000

for i in range(iteration):
    target_data = get_target_data(df, n_target)
    source_data = get_source_data(df, n_source)


    CoRT_model = CoRT_builder.CoRT()
    similar_source_index = CoRT_model.find_similar_source(p, n_target, K, target_data, source_data, T=T, verbose=False)
    X_combined, y_combined = CoRT_model.prepare_CoRT_data(similar_source_index, source_data, target_data)

    N = X_combined.shape[0]
    lamda = CONST_C 

    model = Lasso(alpha=lamda, fit_intercept=False, tol=1e-14, max_iter=1000000)  
    model.fit(X_combined, y_combined.ravel())
    beta_hat_target = model.coef_[-p:]

    M_obs = np.array([i for i, b in enumerate(beta_hat_target) if b != 0])

    if len(M_obs) == 0:
        print(f"Iteration {iter}: Lasso selected no features. Skipping.")

    print(f"M_obs = {M_obs}")

    for i in M_obs:
        if i not in beta_index_dict.keys():
            beta_index_dict[i] = 1
        else:
            beta_index_dict[i] = beta_index_dict[i] + 1

M_obs = [ 7 10]
M_obs = [36]
M_obs = [25 26 40]
M_obs = [25 53]
M_obs = [26 35]
M_obs = [24 27 28]
M_obs = [40]
M_obs = [25 28]
M_obs = [28]
M_obs = [ 1 37]
M_obs = [ 1  7 39 41 54]
M_obs = [26 28 29 40]
M_obs = [ 5 51]
M_obs = [ 3  5  6 29 33 41 43]
M_obs = [25 35 45]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [17 49]
M_obs = [53]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 6  7 10]
M_obs = [36]
M_obs = [25]
M_obs = [21 24 28]
M_obs = [22 23 26 31 39 45]
M_obs = [ 5 25]
M_obs = [25]
M_obs = [25 26 30 35 38 53]
M_obs = [18 36 38]
M_obs = [ 1 19 24 25 26]
M_obs = [19 24 34]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [27]
M_obs = [23 28]
M_obs = [25 35]
M_obs = [28]
M_obs = [25]
M_obs = [25]
M_obs = [ 6  7 20]
M_obs = [24 35]
M_obs = [ 7 10 27 40]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 8 25]
M_obs = [38]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 1  6 23 45 48 56]
M_obs = [ 7 23]
M_obs = [25 33]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [19 25 27 34]
M_obs = [26]
M_obs = [49]
M_obs = [0]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 3 19 29 42 43 46 47]
M_obs = [ 8 25 37 51 56]
M_obs = [27 54]
M_obs = [25]
M_obs = [23 31 43]
M_obs = [24 25 53]
M_obs = [24 32 51 56]
M_obs = [24 36]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [28]
M_obs = [5]
M_obs = [26 54]
M_obs = [ 9 23 36]
M_obs = [49]
M_obs = [20 30 33 45 56]
M_obs = [ 5  7 28 31 40 43 48 56]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 1  2 26]
M_obs = [40]
M_obs = [40 56 57]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.145e-11, tolerance: 1.328e-12
  model = cd_fast.enet_coordinate_descent(

M_obs = [ 8 27]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [27 28]
M_obs = [26 35]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25]
M_obs = [ 8 20 36]
M_obs = [25 26]
M_obs = [25]
M_obs = [ 5 25]
M_obs = [ 8 25 35 36 57]
M_obs = [8]
M_obs = [ 5  8 32]
M_obs = [36]
M_obs = [ 1 26]
M_obs = [35 36 54]
M_obs = [25 40]
M_obs = [ 6  9 33 35 44 45 49 51 53 55]
M_obs = [ 5  8 25]
M_obs = [25 31]
M_obs = [ 5 24 25 27]
M_obs = [30 46 47 51]
M_obs = [ 3  9 26 55 57]
M_obs = [33]
M_obs = [25 36]
M_obs = [24 26]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [7]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [51]
M_obs = [ 7 35]
M_obs = [19]
M_obs = [9]
M_obs = [ 5 17 19 25 28 44 50 53]
M_obs = [ 9 22 40 55]
M_obs = [18 51]
M_obs = [35 39]
M_obs = [25 28]
M_obs = [ 5 25 28]
M_obs = [ 8 27]
M_obs = [25 26]
M_obs = [35 36]
M_obs = [21 30 35 39 40 42]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 26 36]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [18 25]
M_obs = [35 36 56]
M_obs = [25]
M_obs = [ 1  5 28]
M_obs = [35 51]
M_obs = [27 28]
M_obs = [ 9 33 44 54 56]
M_obs = [25 35 40]
M_obs = [ 0  5 25]
M_obs = [40]
M_obs = [25 28 35 36]
M_obs = [ 0 23 26 31 39 45 54]
M_obs = [10 18 21 25 34 36 40 42 51 54]
M_obs = [24 25 40 43]
M_obs = [ 6 19 21 40 51 52]
M_obs = [40]
M_obs = [24 37]
M_obs = [25 28]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 5 25 49]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 5 27]
M_obs = [26 28]
M_obs = [ 1 37]
M_obs = [26]
M_obs = [7]
M_obs = [27]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 6 17 34 36]
M_obs = [ 1 24]
M_obs = [35]
M_obs = [26 28]
M_obs = [37]
M_obs = [34]
M_obs = [5]
M_obs = [18 27]
M_obs = [25]
M_obs = [25 26 28 37]
M_obs = [25]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 7 24 25]
M_obs = [17 18 26]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24 25]
M_obs = [5 7]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25]
M_obs = [26]
M_obs = [8]
M_obs = [26 28]
M_obs = [25]
M_obs = [40 57]
M_obs = [25 35]
M_obs = [ 9 23 32 34]
M_obs = [ 4 25]
M_obs = [ 9 18 28 51]
M_obs = [8]
M_obs = [18 24 25]
M_obs = [25 45]
M_obs = [ 3  9 24]
M_obs = [34]
M_obs = [21 26 34]
M_obs = [40]
M_obs = [46]
M_obs = [27]
M_obs = [24 28]
M_obs = [5]
M_obs = [25 38]
M_obs = [27 28 29 53 54 55 57]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 2 23 27 32 38 42 43 52 55]
M_obs = [24]
M_obs = [19 21 24 25]
M_obs = [24 25]
M_obs = [ 2  9 18 24 35 36]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [20 51]
M_obs = [36]
M_obs = [5]
M_obs = [19 25 27 28]
M_obs = [8]
M_obs = [ 9 25 57]
M_obs = [ 2  3  8 21 26 27 44]
M_obs = [ 5  8 32 38 42]
M_obs = [ 0 26 30 33 38 49 53]
M_obs = [26 32]
M_obs = [25]
M_obs = [ 5 31 36 48 52]
M_obs = [27]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 1 29]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 5 25 27 31 38 56]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [26]
M_obs = [ 3 30 36]
M_obs = [ 0  8 10 19 29 35 43 50]
M_obs = [ 9 40]
M_obs = [ 0  3 25 32 36 42 50 53 55]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25]
M_obs = [17 21 24 27 28 36 37 56]
M_obs = [19 50]
M_obs = [24 25]
M_obs = [34 53]
M_obs = [26]
M_obs = [ 1  5 25 43]
M_obs = [25]
M_obs = [53 57]
M_obs = [30]
M_obs = [ 5 23 45]
M_obs = [27]
M_obs = [25 26 49]
M_obs = [ 3  9 24]
M_obs = [42 54]
M_obs = [26]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 39 57]
M_obs = [ 5 23 25 26]
M_obs = [28]
M_obs = [17 25 33 34 38 53]
M_obs = [33]
M_obs = [ 4 10 32]
M_obs = [1 7]
M_obs = [8]
M_obs = [26 40]
M_obs = [5]
M_obs = [40]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24 25]
M_obs = [40]
M_obs = [10 27 28]
M_obs = [18]
M_obs = [21]
M_obs = [44 45]
M_obs = [23 29 49 55]
M_obs = [ 8 25 27 31 33 37 40 43 55]
M_obs = [39]
M_obs = [ 3 18 19 23 42 43 47 51 52]
M_obs = [24 25 27]
M_obs = [25 28 57]
M_obs = [17 21]
M_obs = [34]
M_obs = [26 35]
M_obs = [24 27]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24 55]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [26]
M_obs = [24]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [28 40]
M_obs = [25]
M_obs = [26 33 44]
M_obs = [36]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 8 40 55]
M_obs = [23 40 56]
M_obs = [26]
M_obs = [27 28]
M_obs = [ 5 17 24 29 31 33 34 41 47]
M_obs = [17 34 50]
M_obs = [25 37]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 1 35 40 42 49]
M_obs = [ 7 24 25 37]
M_obs = [27 57]
M_obs = [ 5 24 25]
M_obs = [25]
M_obs = [25]
M_obs = [1 7]
M_obs = [ 5 25 39]
M_obs = [25 29 40]
M_obs = [24 25]
M_obs = [0 8]
M_obs = [22 23 29 33 39 42 43 55 56]
M_obs = [34]
M_obs = [26 52]
M_obs = [27]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 3  4 18 30 39 42 49 53]
M_obs = [ 3  9 25 27]
M_obs = [7]
M_obs = [24 27 28]
M_obs = [18 26 44]
M_obs = [24 26 28]
M_obs = [26 28]
M_obs = [25 52]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [26 36]
M_obs = [ 6 25 31]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24 26]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 40]
M_obs = [ 4  7 46]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24]
M_obs = [23 34]
M_obs = [42]
M_obs = [25]
M_obs = [28]
M_obs = [ 3 18 20 23 25 36]
M_obs = [17 54 57]
M_obs = [8]
M_obs = [ 8 28]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 27 34 43]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [26 28]
M_obs = [29 49]
M_obs = [ 2  6 26 31]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25]
M_obs = [2]
M_obs = [27]
M_obs = [5]
M_obs = [7]
M_obs = [ 1  5  8 19 25 54]
M_obs = [26 33]
M_obs = [24 25]

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.231e-11, tolerance: 1.442e-12
  model = cd_fast.enet_coordinate_descent(

M_obs = [25 27]
M_obs = [25]
M_obs = [ 0  7 23 24]
M_obs = [ 3 49]
M_obs = [44]
M_obs = [26]
M_obs = [42]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [17]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 2 18 24 25 28 39]
M_obs = [ 0  1 21 40 41 52]
M_obs = [18 21 25]
M_obs = [7]
M_obs = [25 28]
M_obs = [26 42]
M_obs = [ 7 20 25 42]
M_obs = [ 9 24 48]
M_obs = [25]
M_obs = [ 4 25]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [57]
M_obs = [ 4 25 40]
M_obs = [40]
M_obs = [ 3 29 32 36 47 52]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25]
M_obs = [ 1  6  7 25 28 35 40]
M_obs = [7]
M_obs = [ 5 10 25]
M_obs = [18 25 34 44]
M_obs = [ 4 10 23 35 53 55]
M_obs = [ 5 23 37 45 55 57]
M_obs = [28 43]
M_obs = [ 7 19]
M_obs = [ 5 22 27]
M_obs = [25]
M_obs = [ 0 23 36 49 50 54]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 26 35]
M_obs = [25]
M_obs = [25]
M_obs = [26]
M_obs = [ 0 24 29 55 56 57]
M_obs = [ 6  7 10 22 24 29 33 40 45 49]
M_obs = [42 50]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 7 19 35 51 52]
M_obs = [24]
M_obs = [26 45 46 48 50]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 4 35 41]
M_obs = [10 41 49 57]
M_obs = [24]
M_obs = [ 0 30 47 49 56]
M_obs = [ 9 18]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 3 18 29 41 48 55 57]
M_obs = [25 29 35 47 57]
M_obs = [ 5 25 54]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 5  6 25 26 33 43 50 51]
M_obs = [ 7 27]
M_obs = [57]
M_obs = [5]
M_obs = [18 19 25 37]
M_obs = [ 5 22 25 40]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [23 34]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 4 17 34 36 50 53]
M_obs = [26 28]
M_obs = [ 9 25]
M_obs = [1]
M_obs = [ 2 19 24 34]

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.020e-12, tolerance: 1.456e-12
  model = cd_fast.enet_coordinate_descent(

Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [26 55]
M_obs = [10 37]
M_obs = [28 54]
M_obs = [25 26 28]
M_obs = [21 40 57]
M_obs = [ 2 33]
M_obs = [27]
M_obs = [ 5  8 20 34 36 37 41 44 53 55]
M_obs = [18 23 25 36 40]
M_obs = [25 26 39]
M_obs = [19]
M_obs = [25 56]
M_obs = [45]
M_obs = [41]
M_obs = [25 26]
M_obs = [ 7 24 25]
M_obs = [41]
M_obs = [29]
M_obs = [ 3 26 43 50]
M_obs = [ 4 25 26]
M_obs = [26 39]
M_obs = [40 45]
M_obs = [26 28]
M_obs = [21 24 29 50 53 55 56 57]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.743e-12, tolerance: 1.482e-12
  model = cd_fast.enet_coordinate_descent(
c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.399e-12, tolerance: 1.384e-12
  model = cd_fast.enet_coordinate_descent(

M_obs = [ 5 26]
M_obs = [ 5 17]
M_obs = [25]
M_obs = [ 7 24]
M_obs = [21 26]
M_obs = [25]
M_obs = [ 5  8 25]
M_obs = [10 23 25 34 54]
M_obs = [25 50]
M_obs = [26 37]
M_obs = [ 3 46 50]
M_obs = [8]
M_obs = [ 6 18 19 25]
M_obs = [7]
M_obs = [8]
M_obs = [7]
M_obs = [0]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.919e-12, tolerance: 1.407e-12
  model = cd_fast.enet_coordinate_descent(

M_obs = [8]
M_obs = [ 8 25 52]
M_obs = [ 2  4 25 45]
M_obs = [48]
M_obs = [ 0  3 17 21 36 40 45 46 51]
M_obs = [ 7 20 21 25 49]
M_obs = [24 26 40]
M_obs = [25 35]
M_obs = [3 7]
M_obs = [ 2 23]
M_obs = [ 3  5 17 24 25 27 29 37 39 41 42 55]
M_obs = [17 35 36 53]
M_obs = [ 5  8 45 51]
M_obs = [25 40]
M_obs = [54 55]
M_obs = [ 3 19 25 35 40]
M_obs = [53]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 35]
M_obs = [46]
M_obs = [ 2  4 34]
M_obs = [5 8]
M_obs = [ 1 25 28]
M_obs = [26]
M_obs = [25 27]
M_obs = [45]
M_obs = [ 5 25 26 28]
M_obs = [24 25 54]
M_obs = [5]
M_obs = [ 1  8 28 52]
M_obs = [34 36]
M_obs = [25 26]
M_obs = [ 8 10 20 23 29 34 36 55 56 57]
M_obs = [25]
M_obs = [ 5 25 52]

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.373e-12, tolerance: 1.496e-12
  model = cd_fast.enet_coordinate_descent(
c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.939e-11, tolerance: 1.497e-12
  model = cd_fast.enet_coordinate_descent(

M_obs = [ 5 47]
M_obs = [ 9 55]
M_obs = [28 37]
M_obs = [25 27 40]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [39 53 55]
M_obs = [25]
M_obs = [17]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [19 25 48]
M_obs = [ 8 10 25]
M_obs = [10 28 31 36 55 56]
M_obs = [39]
M_obs = [25]
M_obs = [1 5]
M_obs = [34]
M_obs = [30 42 49 55 56]
M_obs = [ 5 37]
M_obs = [49]
M_obs = [ 4 27 28 36]
M_obs = [26]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 1  7 25 36]
M_obs = [24]
M_obs = [ 2 54]
M_obs = [18 37]
M_obs = [17 19 31 44 56]
M_obs = [ 8 33 43 56]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [26]
M_obs = [22 33 41 51 52]
M_obs = [ 5 26 52]
M_obs = [26 28 35 44 51 52]
M_obs = [24 25]
M_obs = [ 4 10]
M_obs = [36]
M_obs = [26]
M_obs = [23 25 36]
M_obs = [ 4 24 27 29 36]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 26 27]

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.185e-11, tolerance: 1.477e-12
  model = cd_fast.enet_coordinate_descent(

M_obs = [24 28]
M_obs = [28]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 8 25 26]
M_obs = [26]
M_obs = [34 41 42 52]
M_obs = [ 3 35 51]
M_obs = [ 0 25 40]
M_obs = [26]
M_obs = [25]
M_obs = [ 8 23 29]
M_obs = [35]
M_obs = [27]
M_obs = [25]
M_obs = [24]
M_obs = [25]
M_obs = [ 5 20]
M_obs = [ 9 52]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [57]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [40]
M_obs = [25 28 37]
M_obs = [ 5 25 55]
M_obs = [24 25 28 52]
M_obs = [25 54]
M_obs = [28]
M_obs = [26 34]
M_obs = [25 26 28]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 5  6 22 23 26 41 44]
M_obs = [18 27]
M_obs = [ 5 23]
M_obs = [ 5 27]
M_obs = [26 28 40]
M_obs = [26 34]
M_obs = [25 27]
M_obs = [ 1  6 21 31 32 35 40 44 48 50 55]
M_obs = [ 7 27]
M_obs = [ 1  5  8 25]
M_obs = [5]
M_obs = [ 0  8 28 31 34 45 55 56]
M_obs = [ 7 35]
M_obs = [36]
M_obs = [25]
M_obs = [26 28 48]
M_obs = [24]
M_obs = [7]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 55 57]
M_obs = [24 25]

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.169e-12, tolerance: 1.234e-12
  model = cd_fast.enet_coordinate_descent(

M_obs = [7]
M_obs = [ 3  9 25 49 51]
M_obs = [18 25 26 55]
M_obs = [26 27 33 41 52]
M_obs = [ 6 40]
M_obs = [6 8]
M_obs = [ 8 26 46]
M_obs = [ 1 37 52]
M_obs = [27 37 44 49 53 55]
M_obs = [24 27]
M_obs = [ 7 20 26]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 5 28]
M_obs = [ 9 40]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [4 5 6]
M_obs = [10 18 24 31 40 43]
M_obs = [29]
M_obs = [ 5  9 29 31 32 37 38 44 56]

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.063e-11, tolerance: 1.500e-12
  model = cd_fast.enet_coordinate_descent(

M_obs = [10 35 37]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [17]
M_obs = [ 3 36]
M_obs = [30 44 50 56]
M_obs = [25 55 57]
M_obs = [ 5 25 26 40]
M_obs = [19 25 26]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 3  5  6 39]
M_obs = [ 5  8 28]
M_obs = [25]
M_obs = [ 1 24 25]
M_obs = [27]
M_obs = [25 28]
M_obs = [ 8 25]
M_obs = [26]
M_obs = [10 25]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24 25 35]
M_obs = [8]
M_obs = [ 7 27]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [34 40]
M_obs = [28 35 36]
M_obs = [39 47]
M_obs = [25]
M_obs = [27 28 40]
M_obs = [35]
M_obs = [ 9 27]
M_obs = [25]
M_obs = [25]
M_obs = [34 43 47 53 57]
M_obs = [9]
M_obs = [1]
M_obs = [ 5 26]
M_obs = [ 5 24]
M_obs = [1]
M_obs = [ 1 20 23 33 43 45 49 56]
M_obs = [25 26]
M_obs = [28]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25]
M_obs = [25]
M_obs = [24 25 45]
M_obs = [17]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 5 33 38 40]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [26 37]
M_obs = [25 30]
M_obs = [ 1 26]
M_obs = [40]
M_obs = [24 25]
M_obs = [ 2  6  9 27 29 52]
M_obs = [ 7 17 24 25]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [26]
M_obs = [28 55]
M_obs = [1]
M_obs = [ 2 18 25]
M_obs = [ 5  6 28 38]
M_obs = [10 31 49 56]
M_obs = [1]
M_obs = [ 6 23 31 43 44 50 51 54 56 57]
M_obs = [26 40 50]
M_obs = [28]
M_obs = [ 9 57]
M_obs = [ 1 22 27 28]
M_obs = [ 7 36]
M_obs = [18 25 28]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 8 18]
M_obs = [35]
M_obs = [26]
M_obs = [25]
M_obs = [40]
M_obs = [ 3 10 25 31]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [26]
M_obs = [ 7 26 40]
M_obs = [23 30 38 51 54 56]
M_obs = [24 36]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 9 35 40]
M_obs = [ 5 25 28]
M_obs = [18 26]
M_obs = [55]
M_obs = [36 45 52]
M_obs = [24 25 27 55 57]
M_obs = [ 1 26]
M_obs = [26]
M_obs = [25]
M_obs = [25 27]
M_obs = [23 25]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24 34 40]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [28]
M_obs = [21]
M_obs = [36 42]
M_obs = [25]
M_obs = [17 28 44]
M_obs = [24 42 43 54]
M_obs = [ 5 20 30 40 49 53 54 55]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [47]
M_obs = [ 0 17 27 33]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 7 24 26 46]
M_obs = [ 5 28]
M_obs = [1]
M_obs = [25 29 46 49 55]
M_obs = [ 8 26]
M_obs = [ 8 25]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 4 18 23 32 44 52]
M_obs = [2 4]
M_obs = [0]
M_obs = [ 5 27 30 38]
M_obs = [23 25]
M_obs = [18 35]
M_obs = [25]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 7 26]
M_obs = [7]
M_obs = [25 40]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24 25 26]
M_obs = [10 25 26 32]
M_obs = [55 57]
M_obs = [26 57]
M_obs = [25]
M_obs = [24 25]
M_obs = [25 51]
M_obs = [19 29 35 36]
M_obs = [ 1 22 23 25 27]
M_obs = [ 5  7 28 33 34 49]
M_obs = [ 8 28 46]
M_obs = [24 25]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 1  5 44]
M_obs = [24 25]
M_obs = [25 36 52]
M_obs = [28]
M_obs = [26]
M_obs = [21 23 24 25 33 38 55]
M_obs = [ 2  6 36 37]
M_obs = [ 8 35]
M_obs = [24 28]
M_obs = [ 8 36]
M_obs = [ 5 24]
M_obs = [ 8 23 27 28 54]
M_obs = [36 49 55]
M_obs = [ 7 25 27]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 0  6  8 29 43 55]
M_obs = [18 29 40]
M_obs = [ 5 25]
M_obs = [28 35]
M_obs = [ 4 25]
M_obs = [24 55 57]
M_obs = [25 30]
M_obs = [24 25]
M_obs = [ 4 18]
M_obs = [26]
M_obs = [24 25 28]
M_obs = [24 25 33 37]
M_obs = [25 28]
M_obs = [20 46]
M_obs = [28 51 55 57]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 8 23 25 26]
M_obs = [ 8 28]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24 51]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 5 19 26]
M_obs = [ 1  8 26]
M_obs = [53]
M_obs = [26]
M_obs = [23]
M_obs = [5]
M_obs = [ 8 25 29 33 44 50]
M_obs = [ 1 26 28]
M_obs = [30 38 51]
M_obs = [ 5 26 28]
M_obs = [25]
M_obs = [25 26 52]
M_obs = [32 49 52]
M_obs = [ 5 33 40]

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.279e-11, tolerance: 1.257e-12
  model = cd_fast.enet_coordinate_descent(

Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 7 27 28 42 45 56 57]
M_obs = [ 3 21 44]
M_obs = [25]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [39 40 52 57]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [10 25 26 32 34 41 42 49 56 57]
M_obs = [25 27 57]
M_obs = [53]
M_obs = [40]
M_obs = [26 28 54]
M_obs = [37]
M_obs = [39]
M_obs = [40]
M_obs = [28 54]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [8 9]
M_obs = [ 1  5 24]
M_obs = [33]
M_obs = [24 27 28 39]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [28]
M_obs = [29]
M_obs = [28]
M_obs = [24 43 51]
M_obs = [18 24]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [27]
M_obs = [1]
M_obs = [26]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [26]
M_obs = [25 35]
M_obs = [23]
M_obs = [25]
M_obs = [ 8 24 29 44]
M_obs = [25 47 51]
M_obs = [33 50]
M_obs = [25 27]
M_obs = [ 5 25]
M_obs = [ 8 17 48]
M_obs = [17 26 28 40]
M_obs = [ 8 25 33 37]
M_obs = [9]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [24 55]
M_obs = [ 2  9 40]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [10 25 36]
M_obs = [24 38 54 57]
M_obs = [17 53]
M_obs = [25 26 56]
M_obs = [29]
M_obs = [ 7 55 57]
M_obs = [ 7 25 40]
M_obs = [25]
M_obs = [43]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 5 18 28]
M_obs = [ 1 25]
M_obs = [ 0 29 30 35 36 38 43 55 57]
M_obs = [26 32 53]
M_obs = [19 25 55 57]
M_obs = [ 3  6 34]
M_obs = [25 42 55]
M_obs = [25]
M_obs = [18 25 29]
M_obs = [26 40]
M_obs = [22 30]
M_obs = [26 51]
M_obs = [25]
M_obs = [0]
M_obs = [39]
M_obs = [25 27]
M_obs = [34 52]
M_obs = [ 9 27 54]
M_obs = [36 40 53]
M_obs = [28]
M_obs = [ 0 26]
M_obs = [25 40]
M_obs = [36 41]
M_obs = [ 0 35 36]
M_obs = [27 41 43]
M_obs = [25]

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.097e-11, tolerance: 1.060e-12
  model = cd_fast.enet_coordinate_descent(
c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.124e-10, tolerance: 1.491e-12
  model = cd_fast.enet_coordinate_descent(

M_obs = [54]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 27]
M_obs = [32 55]
M_obs = [26 27 37]
M_obs = [25 47]
M_obs = [24 51]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25]
M_obs = [24 27 57]
M_obs = [25]
M_obs = [40]
M_obs = [0]
M_obs = [25]
M_obs = [ 5 25 27]
M_obs = [26 57]
M_obs = [26]
M_obs = [40]
M_obs = [ 3 24 25]
M_obs = [ 4  5 26 27]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [42 51 54]
M_obs = [ 5 26 27]
M_obs = [ 0  5 24 43]
M_obs = [25 40 41]
M_obs = [ 9 27 54]
M_obs = [ 5 18 25 29 40 42 45 48 56]
M_obs = [27 41]
M_obs = [ 5  8 26 28 39]
M_obs = [26 45]
M_obs = [19 30 40 44 51 54 55 56]
M_obs = [ 1 25 26 29]
M_obs = [24 35 36 40]
M_obs = [28]
M_obs = [ 7 28 57]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 8 45 56]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 5 28 32 45]
M_obs = [ 5  6 24 30 40 48 55 57]
M_obs = [ 7 24 27]
M_obs = [25 26 35]
M_obs = [26]
M_obs = [18 25 39]
M_obs = [25 26]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [18 36]
M_obs = [25]
M_obs = [25 34 37 39 48]
M_obs = [ 8 25]
M_obs = [ 5 35 39]
M_obs = [18 24 30]
M_obs = [25]
M_obs = [25 30]
M_obs = [5 7]
M_obs = [20]
M_obs = [27 29]
M_obs = [ 2  9 36 40]
M_obs = [26 28 35 52]
M_obs = [24 25]
M_obs = [28]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [ 8 22]
M_obs = [26]
M_obs = [25 29 37]
M_obs = [35]
M_obs = [19]

c:\Users\Hiep\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:716: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.183e-12, tolerance: 1.092e-12
  model = cd_fast.enet_coordinate_descent(

Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 28 43 44]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [25 28]
M_obs = [ 0  5  7  9 10 25 42 55]
M_obs = [25 28 29]
M_obs = [ 9 25]
M_obs = [27 28]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [9]
M_obs = [24 25 28]
M_obs = [25 26 27 28]
M_obs = [24 25 27]
M_obs = [40]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []
M_obs = [7]
M_obs = [5]
M_obs = [5]
M_obs = [24 28 32 42]
M_obs = [ 2 10]
Iteration <built-in function iter>: Lasso selected no features. Skipping.
M_obs = []

In [23]:
sorted_dict = dict(sorted(beta_index_dict.items(), key=lambda item: item[1], reverse=True))
sorted_dict

{np.int64(25): 309,
 np.int64(26): 162,
 np.int64(24): 131,
 np.int64(28): 120,
 np.int64(5): 113,
 np.int64(27): 96,
 np.int64(40): 85,
 np.int64(8): 71,
 np.int64(36): 67,
 np.int64(7): 65,
 np.int64(35): 62,
 np.int64(55): 57,
 np.int64(1): 47,
 np.int64(18): 47,
 np.int64(57): 47,
 np.int64(23): 46,
 np.int64(34): 44,
 np.int64(9): 41,
 np.int64(29): 41,
 np.int64(49): 40,
 np.int64(56): 37,
 np.int64(51): 34,
 np.int64(54): 34,
 np.int64(33): 33,
 np.int64(3): 32,
 np.int64(37): 32,
 np.int64(19): 31,
 np.int64(43): 31,
 np.int64(42): 30,
 np.int64(53): 30,
 np.int64(52): 30,
 np.int64(39): 29,
 np.int64(45): 29,
 np.int64(44): 28,
 np.int64(10): 28,
 np.int64(0): 27,
 np.int64(6): 26,
 np.int64(17): 26,
 np.int64(32): 25,
 np.int64(30): 24,
 np.int64(21): 23,
 np.int64(41): 22,
 np.int64(4): 22,
 np.int64(2): 22,
 np.int64(31): 21,
 np.int64(38): 20,
 np.int64(50): 20,
 np.int64(46): 17,
 np.int64(47): 16,
 np.int64(20): 16,
 np.int64(48): 15,
 np.int64(22): 13}

In [ ]:
df.columns

Index([' n_tokens_title', ' n_tokens_content', ' n_unique_tokens',
       ' n_non_stop_words', ' n_non_stop_unique_tokens', ' num_hrefs',
       ' num_self_hrefs', ' num_imgs', ' num_videos', ' average_token_length',
       ' num_keywords', ' data_channel_is_lifestyle',
       ' data_channel_is_entertainment', ' data_channel_is_bus',
       ' data_channel_is_socmed', ' data_channel_is_tech',
       ' data_channel_is_world', ' kw_min_min', ' kw_max_min', ' kw_avg_min',
       ' kw_min_max', ' kw_max_max', ' kw_avg_max', ' kw_min_avg',
       ' kw_max_avg', ' kw_avg_avg', ' self_reference_min_shares',
       ' self_reference_max_shares', ' self_reference_avg_sharess',
       ' weekday_is_monday', ' weekday_is_tuesday', ' weekday_is_wednesday',
       ' weekday_is_thursday', ' weekday_is_friday', ' weekday_is_saturday',
       ' weekday_is_sunday', ' is_weekend', ' LDA_00', ' LDA_01', ' LDA_02',
       ' LDA_03', ' LDA_04', ' global_subjectivity',
       ' global_sentiment_polarity', ' global_rate_positive_words',
       ' global_rate_negative_words', ' rate_positive_words',
       ' rate_negative_words', ' avg_positive_polarity',
       ' min_positive_polarity', ' max_positive_polarity',
       ' avg_negative_polarity', ' min_negative_polarity',
       ' max_negative_polarity', ' title_subjectivity',
       ' title_sentiment_polarity', ' abs_title_subjectivity',
       ' abs_title_sentiment_polarity', ' shares'],
      dtype='object')

In [ ]:
import utils
import parametric

import warnings
from sklearn.exceptions import ConvergenceWarning

# Filter out this specific warning
warnings.filterwarnings("ignore", category=ConvergenceWarning)

p = df.shape[1] - 1
K = 5
T = 5
CONST_C = 25

target_data = get_target_data(df, n_target)
source_data = get_source_data(df, n_source)

Sigma = estimate_Sigma(target_data["X"], target_data["y"], n_target)

CoRT_model = CoRT_builder.CoRT()
similar_source_index = CoRT_model.find_similar_source(p, n_target, K, target_data, source_data, T=T, verbose=False)
X_combined, y_combined = CoRT_model.prepare_CoRT_data(similar_source_index, source_data, target_data)

N = X_combined.shape[0]
lamda = CONST_C 

model = Lasso(alpha=lamda / N, fit_intercept=False, tol=1e-14, max_iter = 1000000)
model.fit(X_combined, y_combined.ravel())
beta_hat_target = model.coef_[-p:]

M_obs = np.array([i for i, b in enumerate(beta_hat_target) if b != 0])

if len(M_obs) == 0:
    print(f"Iteration {iter}: Lasso selected no features. Skipping.")

print(f"M_obs = {M_obs}")

for i in M_obs:
    if i not in beta_index_dict.keys():
        beta_index_dict[i] = 1
    else:
        beta_index_dict[i] = beta_index_dict[i] + 1

j = np.random.choice(len(M_obs))
selected_feature_index = M_obs[j]

X_target = target_data["X"]
y_target = target_data["y"]
X_active, X_inactive = utils.get_active_X(beta_hat_target, X_target)

etaj, etajTy = utils.construct_test_statistic(y_target, j, X_active)

Sigma = np.eye(n_target)
b_global = Sigma @ etaj @ np.linalg.pinv(etaj.T @ Sigma @ etaj)
a_global = (Sigma - b_global @ etaj.T) @ y_target

folds = utils.split_target(T, X_target, y_target, n_target)

tn_sigma = (np.sqrt(etaj.T @ Sigma @ etaj)).item()
z_min = -20  * tn_sigma
z_max = 20 * tn_sigma
z_interval = parametric.solve_truncation_CoRT(z_min, z_max, X_target, folds, source_data, a_global, b_global, p, K, T, M_obs)
p_value = utils.pivot(z_interval, etaj, etajTy, 0, Sigma)
print(p_value)

M_obs = [10 23 25 31 34 37 39 40 45 50]
len(z_interval): 0
denominator is zero in pivot calculation
None

In [ ]:
z_interval

[]

In [ ]:
p_lambda

58